<?php

namespace UrenBundle\Repository;

/**
 * time_registrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class time_registrationRepository extends \Doctrine\ORM\EntityRepository
{
}
